builders:
  mappable:
    import: "package:object_mapper_builder/builder.dart"
    builder_factories: ["mappableBuilder"]
    build_extensions: {".dart": [".mappable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
